I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 254, in script
    $ result = _result
  File "game/scripts/script.rpy", line 254, in <module>
    $ result = _result
NameError: name '_result' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 254, in script
    $ result = _result
  File "C:\Users\olivi\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\olivi\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/script.rpy", line 254, in <module>
    $ result = _result
NameError: name '_result' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
The Studio 1.0
Fri Jul  4 11:01:41 2025
